# Autogenerated wrapper script for METIS4_jll for i686-w64-mingw32
export libmetis4

JLLWrappers.@generate_wrapper_header("METIS4")
JLLWrappers.@declare_library_product(libmetis4, "libmetis4.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmetis4,
        "bin\\libmetis4.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
