# Autogenerated wrapper script for METIS4_jll for x86_64-w64-mingw32
export libmetis_a

JLLWrappers.@generate_wrapper_header("METIS4")
JLLWrappers.@declare_file_product(libmetis_a)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        libmetis_a,
        "lib\\libmetis.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
